ai architect
cloud architect
business intelligence analyst
network/cloud administrator
IOT specialist

In [1]:
import pandas as pd
import numpy as np

import requests
import bs4
from bs4 import BeautifulSoup

In [2]:
url = "https://www.worldometers.info/coronavirus/"

In [3]:
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')

In [5]:
table = soup.find(name = 'table', attrs = {'id': 'main_table_countries'})

In [25]:
dataframe = pd.read_html(str(table))[0]

In [22]:
dataframe['TotalCases'][0]

80880

In [27]:
dataframe = dataframe.iloc[:-1, :]

In [28]:
dataframe

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,"Serious,Critical",TotÂ Cases/1M pop
0,China,80880,+36,3213.0,14.0,67769.0,9898,3226.0,56.2
1,Italy,24747,NaN,1809.0,NaN,2335.0,20603,1672.0,409.3
2,Iran,14991,"+1,053",853.0,129.0,4590.0,9548,NaN,178.5
3,Spain,8794,+806,297.0,3.0,517.0,7980,272.0,188.1
4,S. Korea,8236,+74,75.0,NaN,1137.0,7024,59.0,160.6
5,Germany,6215,+402,13.0,NaN,46.0,6156,2.0,74.2
6,France,5423,NaN,127.0,NaN,12.0,5284,400.0,83.1
7,USA,3802,+122,69.0,1.0,73.0,3660,10.0,11.5
8,Switzerland,2218,+1,15.0,1.0,4.0,2199,NaN,256.3
9,UK,1391,NaN,35.0,NaN,20.0,1336,20.0,20.5
10,Norway,1282,+26,3.0,NaN,1.0,1278,27.0,236.5
11,Netherlands,1135,NaN,20.0,NaN,2.0,1113,45.0,66.2
12,Belgium,1058,+172,5.0,1.0,1.0,1052,33.0,91.3
13,Sweden,1043,+3,6.0,3.0,1.0,1036,2.0,103.3
14,Austria,1018,+158,2.0,1.0,8.0,1008,1.0,113.0
15,Denmark,898,+34,4.0,2.0,1.0,893,2.0,155.0
16,Japan,845,+6,27.0,3.0,144.0,674,36.0,6.7
17,Diamond Princess,696,NaN,7.0,NaN,456.0,233,15.0,NaN
18,Malaysia,553,+125,NaN,NaN,42.0,511,9.0,17.1
19,Qatar,401,NaN,NaN,NaN,4.0,397,NaN,139.2
20,Australia,375,+75,5.0,NaN,27.0,343,1.0,14.7
21,Canada,341,NaN,1.0,NaN,11.0,329,1.0,9.0
22,Greece,331,NaN,4.0,NaN,8.0,319,5.0,31.8
23,Czechia,298,+5,NaN,NaN,NaN,298,2.0,27.8
24,Finland,277,+33,NaN,NaN,10.0,267,1.0,50.0
25,Israel,255,+42,NaN,NaN,4.0,251,4.0,29.5
26,Portugal,245,NaN,NaN,NaN,3.0,242,9.0,24.0
27,Singapore,226,NaN,NaN,NaN,105.0,121,11.0,38.6
28,Bahrain,221,+7,1.0,1.0,77.0,143,1.0,129.9
29,Slovenia,219,NaN,1.0,NaN,NaN,218,3.0,105.3
...,...,...,...,...,...,...,...,...,...
129,Monaco,2,NaN,NaN,NaN,NaN,2,NaN,NaN
130,Nigeria,2,NaN,NaN,NaN,1.0,1,NaN,NaN
131,Aruba,2,NaN,NaN,NaN,NaN,2,NaN,NaN
132,CuraÃ§ao,2,NaN,NaN,NaN,NaN,2,NaN,NaN
133,DRC,2,NaN,NaN,NaN,NaN,2,NaN,NaN
134,Namibia,2,NaN,NaN,NaN,NaN,2,NaN,0.8
135,Saint Lucia,2,NaN,NaN,NaN,NaN,2,NaN,NaN
136,Saint Martin,2,NaN,NaN,NaN,NaN,2,NaN,NaN
137,Sudan,1,NaN,1.0,NaN,NaN,0,NaN,NaN
138,Nepal,1,NaN,NaN,NaN,1.0,0,NaN,NaN
139,Antigua and Barbuda,1,NaN,NaN,NaN,NaN,1,NaN,NaN
140,Bahamas,1,NaN,NaN,NaN,NaN,1,NaN,NaN
141,Bhutan,1,NaN,NaN,NaN,NaN,1,NaN,NaN
142,Cayman Islands,1,NaN,NaN,NaN,NaN,1,NaN,NaN
143,CAR,1,NaN,NaN,NaN,NaN,1,NaN,0.2
144,Congo,1,NaN,NaN,NaN,NaN,1,NaN,0.2
145,Equatorial Guinea,1,NaN,NaN,NaN,NaN,1,NaN,0.7
146,Gabon,1,NaN,NaN,NaN,NaN,1,NaN,0.4
147,Gibraltar,1,NaN,NaN,NaN,1.0,0,NaN,NaN
148,Guinea,1,NaN,NaN,NaN,NaN,1,NaN,0.1
149,Vatican City,1,NaN,NaN,NaN,NaN,1,NaN,NaN
150,Liberia,1,+1,NaN,NaN,NaN,1,NaN,0.2
151,Mauritania,1,NaN,NaN,NaN,NaN,1,NaN,0.2
152,Mayotte,1,NaN,NaN,NaN,NaN,1,NaN,NaN
153,Mongolia,1,NaN,NaN,NaN,NaN,1,NaN,0.3
154,St. Vincent Grenadines,1,NaN,NaN,NaN,NaN,1,NaN,NaN
155,Suriname,1,NaN,NaN,NaN,NaN,1,NaN,NaN
156,Eswatini,1,NaN,NaN,NaN,NaN,1,NaN,0.9
157,Togo,1,NaN,NaN,NaN,NaN,1,NaN,0.1
158,U.S. Virgin Islands,1,NaN,NaN,NaN,NaN,1,NaN,NaN